**Автор: Анна Смелова**

In [1]:
import numpy as np
import copy

## Решение домашнего задания к уроку 6 “Системы линейных уравнений. Часть 1”

### 1. Задача
#### Решить систему уравнений методом Гаусса:
$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

**<font color='darkblue'>Решение:</font>**<br>
Преобразуем расширенную матрицу:<br>
$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
2 & 1 & -1 & 1 \\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix} \rightarrow \begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & -1 & 1 & 5 \\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix} \rightarrow \begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & 1 & -1 & -5 \\ 
0 & 0 & 1 & -\frac{3}{2}
\end{matrix}\right|
\begin{matrix}
0\\ 
2\\
-2
\end{matrix}
\end{pmatrix}$<br>
Перейдем обратно к системе:<br>
$\begin{cases}
x_3 = \frac{3}{2}x_4 - 2, \\
x_2 = x_3 + 5x_4 + 2, \\
x_1 = -x_2 + x_3 +2x_4
\end{cases} \Leftrightarrow \begin{cases}
x_3 = \frac{3}{2}x_4 - 2, \\
x_2 = \frac{3}{2}x_4 + 5x_4, \\
x_1 = -\frac{13}{2}x_4 + \frac{3}{2}x_4 - 2 + 2x_4
\end{cases} \Leftrightarrow \begin{cases}
x_1 = -3x_4 - 2, \\
x_2 = \frac{13}{2}x_4, \\
x_3 = \frac{3}{2}x_4 - 2
\end{cases}$<br>
Система имеет бесконечное множество решений. Запишем решение в общем виде:<br>
Пусть $x_4=a, a\in \mathbb {R}$, тогда искомое решение: $x=(-3a-2,\frac{13}{2}a,\frac{3}{2}a-2,a)$.<br>
Подставив общее решение в исходную систему, получим тождества:
$\begin{cases}
-3a-2+\frac{13}{2}a-\frac{3}{2}a+2-2a=0,\\
-6a-4+\frac{13}{2}a-\frac{3}{2}a+2+a=-2,\\
-3a-2+\frac{13}{2}a-\frac{9}{2}a+6+a=4.
\end{cases}$.

### 2. Задача
#### Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:
   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

**<font color='darkblue'>Решение:</font>**<br>
а) $\begin{pmatrix}
\left.\begin{matrix}
3 & -1 & 1 \\ 
2 & -5 & -3 \\ 
1 & 1 & -1
\end{matrix}\right|
\begin{matrix}
4\\ 
-17\\
0
\end{matrix}
\end{pmatrix}$<br>
Число уравнений равно числу неизвестных.<br><br>
**...в случае, когда число уравнений равно числу неизвестных и матрица коэффициентов невырождена, если векторы столбцов коэффициентов  𝑎1,𝑎2,...,𝑎𝑛  линейно независимы, то такая система совместна, и ее решение единственно при любом векторе свободных членов  𝑏 ...**<br><br>
Вычислим определитель и ранг матрицы $A$:

In [2]:
A = np.array([[3,-1,1], [2,-5,-3], [1,1,-1]])
print(f'Матрица A:\n {A}')
print(f'Определитель A:\n {np.linalg.det(A):.0f}')
print(f'Ранг матрицы A: {np.linalg.matrix_rank(A)}')

Матрица A:
 [[ 3 -1  1]
 [ 2 -5 -3]
 [ 1  1 -1]]
Определитель A:
 32
Ранг матрицы A: 3


Определитель матрицы коэффициентов $31\neq0$, значит матрица невырождена. Ранг матрицы равен 3, значит векторы столбцов коэффициентов линейно независимы. Следовательно, исследуемая система уравнений **совместна** и имеет **единственное решение**.<br><br>
б) $\begin{pmatrix}
\left.\begin{matrix}
2 & -4 & 6 \\ 
1 & -2 & 3 \\ 
3 & -6 & 9
\end{matrix}\right|
\begin{matrix}
1\\ 
-2\\
5
\end{matrix}
\end{pmatrix}$<br>
Число уравнений равно числу неизвестных.<br>
При этом векторы коэффициентов линейно зависимы, и вектор свободных членов не принадлежит одномерному подпространству, которое они образуют. Решим систему уравнений методом Гаусса:<br>
$\begin{pmatrix}
\left.\begin{matrix}
2 & -4 & 6 \\ 
1 & -2 & 3 \\ 
3 & -6 & 9
\end{matrix}\right|
\begin{matrix}
1\\ 
-2\\
5
\end{matrix}
\end{pmatrix} \rightarrow \begin{pmatrix}
\left.\begin{matrix}
1 & -2 & 3 \\ 
0 & 0 & 0 \\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
-2\\ 
5\\
11
\end{matrix}
\end{pmatrix}$<br>
Следовательно, данная система **несовместна**.<br><br>
в) $\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 5 \\ 
3 & 1 & -8 
\end{matrix}\right|
\begin{matrix}
4\\ 
-2
\end{matrix}
\end{pmatrix}$<br>
Число уравнений меньше числа неизвестных.<br>
$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 5 \\ 
3 & 1 & -8 
\end{matrix}\right|
\begin{matrix}
4\\ 
-2
\end{matrix}
\end{pmatrix} \rightarrow \begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 5 \\ 
0 & 5 & 23 
\end{matrix}\right|
\begin{matrix}
4\\ 
14
\end{matrix}
\end{pmatrix} \Rightarrow \begin{cases}
x_2 = \frac{14-23x_3}{5}, \\
x_1 = 4-5x_3-2x_2, 
\end{cases} \Leftrightarrow \begin{cases}
x_2 = \frac{14-23x_3}{5}, \\
x_1 = \frac{-8+21x_3}{5}, 
\end{cases}$<br>
Система **совместна** и имеет **бесконечное множество решений**. Запишем решение в общем виде:<br>
Пусть $x_3=a, a\in \mathbb {R}$, тогда искомое решение: $x=(\frac{21a-8}{5},\frac{14-23a}{5},a)$.

### 3. Задача
#### Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей
$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

**<font color='darkblue'>Решение:</font>**<br>
Число уравнений равно числу неизвестных.<br>
Так как ранг матрицы коэффициентов и ранг расширенной матрицы равны между собой и равны 4, т.е. числу неизвестных, следовательно, данная система линейных уравнений **совместна и определена**(имеет единственное решение).

In [3]:
A = np.array([[1,3,-2,4], [0,5,0,1], [0,0,3,0], [0,0,0,2]])
print(f'Матрица A:\n {A}')
A_ = np.array([[1,3,-2,4,3], [0,5,0,1,2], [0,0,3,0,4], [0,0,0,2,1]])
print(f'Расширенная матрица A_:\n {A_}')
print(f'Ранг матрицы A: {np.linalg.matrix_rank(A)}')
print(f'Ранг матрицы расширенной A_: {np.linalg.matrix_rank(A_)}')

Матрица A:
 [[ 1  3 -2  4]
 [ 0  5  0  1]
 [ 0  0  3  0]
 [ 0  0  0  2]]
Расширенная матрица A_:
 [[ 1  3 -2  4  3]
 [ 0  5  0  1  2]
 [ 0  0  3  0  4]
 [ 0  0  0  2  1]]
Ранг матрицы A: 4
Ранг матрицы расширенной A_: 4


In [4]:
# Проверка
b = np.array([3,2,4,1])
print(f'x={np.linalg.solve(A,b)}')

x=[2.76666667 0.3        1.33333333 0.5       ]


### 4. Задача
#### Дана система линейных уравнений, заданная расширенной матрицей. Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.
$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

**<font color='darkblue'>Решение:</font>**<br><br>
**...если $rankA<rank \tilde A$, то система несовместна...**<br><br>

In [5]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(f'Матрица A:\n {A}')
print(f'Ранг матрицы A: {np.linalg.matrix_rank(A)}')

Матрица A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Ранг матрицы A: 2


Ранг матрицы коэффициентов равен 2, следовательно, чтобы система была несовместна, надо подобрать такие параметры $a$, $b$ и $c$, при которых ранг расширенной матрицы будет равен 3.<br>
Преобразуем расширенную матрицу:<br>
$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix} \rightarrow \begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & -6 & -12
\end{matrix}\right|
\begin{matrix}
a\\ 
b-4a\\
c-7a
\end{matrix}
\end{pmatrix} \rightarrow \begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & 1 & 2\\ 
0 & 1 & 2
\end{matrix}\right|
\begin{matrix}
a\\ 
\frac{b-4a}{-3}\\
\frac{c-7a}{-6}
\end{matrix}
\end{pmatrix}$<br>
Следовательно, искомое соотношение: $\frac{b-4a}{-3}\neq\frac{c-7a}{-6} \Leftrightarrow$<br> $$2b-c\neq a$$
Возьмем, например, $a=3,b=1,c=1$:

In [6]:
A_ = np.array([[1,2,3,3], [4,5,6,1], [7,8,9,1]])
print(f'Расширенная матрица A_:\n {A_}')
print(f'Ранг расширенной матрицы A_: {np.linalg.matrix_rank(A_)}')

Расширенная матрица A_:
 [[1 2 3 3]
 [4 5 6 1]
 [7 8 9 1]]
Ранг расширенной матрицы A_: 3


## Решение домашнего задания к уроку 7 “Системы линейных уравнений. Часть 2”

### 1. Задача
#### Решить систему уравнений методом Крамера:
а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

**<font color='darkblue'>Решение:</font>**<br>
а) Количество уравнений совпадает с количеством неизвестных.<br>
Найдем определитель матрицы коэффициентов:<br>
$detA=\begin{vmatrix}
1 & -2\\ 
3 & -4 
\end{vmatrix}=
-4+6=2\neq 0,$
следовательно, система совместна.<br>
Найдем определители $detA_{1}$, $detA_{2}$:<br>
$detA_{1}=\begin{vmatrix}
1 & -2\\ 
7 & -4
\end{vmatrix}=
=-4+14=10,$<br>
$detA_{2}=\begin{vmatrix}
1 & 1\\ 
3 & 7
\end{vmatrix}=
=7-3=4$<br>
Найдем решение по формулам Крамера:<br>
$x_{1} = \frac{detA_{1}}{detA} = \frac{10}{2}=5,$<br>
$x_{2} = \frac{detA_{2}}{detA} = \frac{4}{2}=2$<br>
**Ответ: (5,2)**<br><br>
б) Количество уравнений совпадает с количеством неизвестных.<br>
Найдем определитель матрицы коэффициентов:<br>
$detA=\begin{vmatrix}
2 & -1 & 5\\ 
1 & 1 & -3\\
2 & 4 & 1
\end{vmatrix}=
2+6+20-10+24+1=43\neq 0,$
следовательно, система совместна.<br>
Найдем определители $detA_{1}$, $detA_{2}$, $detA_{3}$:<br>
$detA_{1}=\begin{vmatrix}
10 & -1 & 5\\ 
-2 & 1 & -3\\
1 & 4 & 1
\end{vmatrix}=
=10-40+3-5+120-2=86,$<br>
$detA_{2}=\begin{vmatrix}
2 & 10 & 5\\ 
1 & -2 & -3\\
2 & 1 & 1
\end{vmatrix}=
=-4+5-60+20+6-10=-43$<br>
$detA_{3}=\begin{vmatrix}
2 & -1 & 10\\ 
1 & 1 & -2\\
2 & 4 & 1
\end{vmatrix}=
=2+40+4-20+16+1=43$<br>
Найдем решение по формулам Крамера:<br>
$x_{1} = \frac{detA_{1}}{detA} = \frac{86}{43}=2,$<br>
$x_{2} = \frac{detA_{2}}{detA} = \frac{-43}{43}=-1$<br>
$x_{3} = \frac{detA_{3}}{detA} = \frac{43}{43}=1$<br>
**Ответ: (2,-1,1)**<br><br>

In [7]:
# Проверка - численное решение
# а)
A_a = np.array([[1,-2],[3,-4]])
b_a = np.array([1,7])
print(f'x_a={np.linalg.solve(A_a,b_a)}')
# б)
A_b = np.array([[2,-1,5],[1,1,-3],[2,4,1]])
b_b = np.array([10,-2,1])
print(f'x_b={np.linalg.solve(A_b,b_b)}')

x_a=[5. 2.]
x_b=[ 2. -1.  1.]


### 2*. Задача
#### Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:
а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

**<font color='darkblue'>Решение:</font>**<br>
а) Друг под другом: сверху формируем матрицу $U$, снизу матрицу $L$:<br>
U: $\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}\rightarrow
\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 20 & 18
\end{pmatrix}\rightarrow
\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix}=U$<br>
L: $\begin{pmatrix}
1 & 0 & 0 \\ 
l_{21} & 1 & 0 \\ 
l_{31} & l_{32} & 1
\end{pmatrix}\rightarrow
\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & l_{32} & 1
\end{pmatrix}\rightarrow
\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}=L$<br><br>
$\Rightarrow \begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix} = \begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}
\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix}$<br><br>
б) Друг под другом: сверху формируем матрицу $U$, снизу матрицу $L$:<br>
U: $\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix} \rightarrow 
\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 15 & 23 & 6\\
0 & 18 & 45 & 17
\end{pmatrix} \rightarrow 
\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 21 & 11
\end{pmatrix} \rightarrow 
\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 0 & 4
\end{pmatrix}=U$<br>
L: $\begin{pmatrix}
1 & 0 & 0 & 0\\ 
l_{21} & 1 & 0 & 0\\ 
l_{31} & l_{32} & 1 & 0\\
l_{41} & l_{42} & l_{43} & 1
\end{pmatrix} \rightarrow
\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & l_{32} & 1 & 0\\
4 & l_{42} & l_{43} & 1
\end{pmatrix} \rightarrow
\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & 1 & 0\\
4 & 6 & l_{43} & 1
\end{pmatrix} \rightarrow
\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & 1 & 0\\
4 & 6 & 7 & 1
\end{pmatrix}=L$<br><br>
$\Rightarrow \begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}=\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & 1 & 0\\
4 & 6 & 7 & 1
\end{pmatrix}
\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 0 & 4
\end{pmatrix}$

### 3*. Задача
#### Решить систему линейных уравнений методом $LU$-разложения
$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

**<font color='darkblue'>Решение:</font>**<br>
Немного преобразуем исходную матрицу для простоты вычислений:<br>
$\begin{pmatrix}
\left.\begin{matrix}
2 & 1 & 3\\ 
11 & 7 & 5\\ 
9 & 8 & 4
\end{matrix}\right|
\begin{matrix}
1\\ 
-6\\
-5
\end{matrix}
\end{pmatrix} \rightarrow 
\begin{pmatrix}
\left.\begin{matrix}
2 & 1 & 3\\ 
22 & 14 & 10\\ 
18 & 16 & 8
\end{matrix}\right|
\begin{matrix}
1\\ 
-12\\
-10
\end{matrix}
\end{pmatrix}$<br><br>
Друг под другом: сверху формируем матрицу $U$, снизу матрицу $L$:<br>
U: $\begin{pmatrix}
2 & 1 & 3 \\ 
22 & 14 & 10 \\ 
18 & 16 & 8
\end{pmatrix} \rightarrow
\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 3 & -23 \\ 
0 & 7 & -19
\end{pmatrix} \rightarrow
\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 3 & -23 \\ 
0 & 0 & \frac{104}{3}
\end{pmatrix}=U$<br>
L: $\begin{pmatrix}
1 & 0 & 0 \\ 
l_{21} & 1 & 0 \\ 
l_{31} & l_{32} & 1
\end{pmatrix} \rightarrow
\begin{pmatrix}
1 & 0 & 0 \\ 
11 & 1 & 0 \\ 
9 & l_{32} & 1
\end{pmatrix} \rightarrow
\begin{pmatrix}
1 & 0 & 0 \\ 
11 & 1 & 0 \\ 
9 & \frac{7}{3} & 1
\end{pmatrix}=L$<br><br>
Решим систему $Ly=b$:<br>
$\begin{cases}
y_1=1 \\
11y_{1}+y_2=-12 \\
9y_{1}+\frac{7}{3}y_{2}+y_{3}=-10
\end{cases} \Leftrightarrow
\begin{cases}
y_1=1 \\
y_2=-23 \\
y_{3}=\frac{104}{3}
\end{cases}$<br><br>
Решим систему $Ux=y$:<br>
$\begin{cases}
2x_1+x_2+3x_3=1 \\
3x_2-23x_3=-23 \\
\frac{104}{3}x_3=\frac{104}{3}
\end{cases} \Leftrightarrow
\begin{cases}
x_1=-1 \\
x_2=0 \\
x_3=1
\end{cases}$<br>
**Ответ: (-1,0,1)**

### 4*. Задача
#### Решить систему линейных уравнений методом Холецкого
$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

**<font color='darkblue'>Решение:</font>**<br>
Произведем разложение на $LL^{T}$:
$l_{11}=\sqrt{a_{11}}=\sqrt{81}=9,$<br>
$l_{21}=\frac{a_{21}}{l_{11}}=\frac{-45}{9}=-5,$<br>
$l_{31}=\frac{a_{31}}{l_{11}}=\frac{45}{9}=5,$<br>
$l_{22}=\sqrt{a_{22}-l_{21}^{2}}=\sqrt{50 - 25}=\sqrt{25}=5,$<br>
$l_{32}=\frac{1}{l_{22}}\left ( a_{32}-l_{21}l_{31} \right)=\frac{1}{5}(-15+25)=\frac{10}{5}=2,$<br>
$l_{33}=\sqrt{a_{33}-l_{31}^{2}-l_{32}^{2}}=\sqrt{38-25-4}=\sqrt{9}=3.$<br><br>
Получили матрицу 
$L = \begin{pmatrix}
9 & 0 & 0 \\ 
-5 & 5 & 0 \\ 
5 & 2 & 3
\end{pmatrix}, 
\; \;
L^{T} = \begin{pmatrix}
9 & -5 & 5 \\ 
0 & 5 & 2 \\ 
0 & 0 & 3
\end{pmatrix}.$<br><br>
Решим систему $Ly=b:$<br>
$\begin{cases}
9y_1=531, \\
-5y_1+5y_2=-460, \\
5y_1+2y_2+3y_3=193.
\end{cases} \Leftrightarrow
\begin{cases}
y_1=59, \\
y_2=-33, \\
y_3=-12.
\end{cases}$<br><br>
И решим систему $L^{T}x=y:$<br>
$\begin{cases}
9x_1-5x_2+5x_3=59, \\
5x_2+2x_3=-33, \\
3x_{3}=-12.
\end{cases} \Leftrightarrow
\begin{cases}
x_1=6, \\
x_2=-5, \\
x_3=-4.
\end{cases}$<br>
**Ответ: (6,-5,-4)**

In [8]:
# Проверка - численное решение
A = np.array([[81,-45,45],[-45,50,-15],[45,-15,38]])
b = np.array([531,-460,193])
print(f'x={np.linalg.solve(A,b)}')

x=[ 6. -5. -4.]


### 5*. Задача
#### Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

**<font color='darkblue'>Решение:</font>**<br>

In [9]:
def solve_by_Cramer(A,b):
    x = []
    det_A = np.linalg.det(A)
    A_T = A.T
    for i in range(len(A_T)):
        Ai = copy.deepcopy(A_T)
        Ai[i] = b
        det_Ai = np.linalg.det(Ai.T)
        x.append(det_Ai / det_A)
    return x 

In [10]:
A = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
b = np.array([10, -2, 1])
print(f'A={A}')
print(f'b={b}')

A=[[ 2 -1  5]
 [ 1  1 -3]
 [ 2  4  1]]
b=[10 -2  1]


In [11]:
solve_by_Cramer(A,b)

[2.0000000000000018, -1.0000000000000009, 1.0]